#!/usr/bin/bash

# just accurate match. If the swww-daemon is running, then
if ! pgrep -x "swww-daemon" > /dev/null; then
    swww-daemon &
    sleep 0.5
fi

swww img "$1" \
    --transition-type grow \
    --transition-pos "$(hyprctl cursorpos)" \
    --transition-duration 3
